In [64]:
import pandas as pd

In [65]:
df = pd.read_csv('salaries_by_college_major.csv')

In [66]:
df.head(5)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

How many rows does our dataframe have?

How many columns does it have?

What are the labels for the columns? Do the columns have names?

Are there any missing values in our dataframe? Does our dataframe contain any bad data?

In [67]:
df.shape # number of rows, columns

(51, 6)

In [68]:
df.columns # column names

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [69]:
for col in df.columns:
  print(f'number of nan in {col}: {df[col].isna().sum()}')

number of nan in Undergraduate Major: 0
number of nan in Starting Median Salary: 1
number of nan in Mid-Career Median Salary: 1
number of nan in Mid-Career 10th Percentile Salary: 1
number of nan in Mid-Career 90th Percentile Salary: 1
number of nan in Group: 1

In [70]:
clean_df = df.dropna()

In [71]:
for col in clean_df.columns:
  print(f'number of nan in {col}: {clean_df[col].isna().sum()}')

number of nan in Undergraduate Major: 0
number of nan in Starting Median Salary: 0
number of nan in Mid-Career Median Salary: 0
number of nan in Mid-Career 10th Percentile Salary: 0
number of nan in Mid-Career 90th Percentile Salary: 0
number of nan in Group: 0

In [72]:
clean_df.shape

(50, 6)

In [73]:
index_with_max_salary_starting= clean_df['Starting Median Salary'].idxmax()

In [74]:
clean_df['Undergraduate Major'].loc[index_with_max_salary_starting]

'Physician Assistant'

In [75]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

1. What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience).

2. Which college major has the lowest starting salary and how much do graduates earn after university?

3. Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?

In [76]:
#1
index_with_max_salary_mid = clean_df['Mid-Career Median Salary'].idxmax()
clean_df['Undergraduate Major'].loc[index_with_max_salary_mid]
clean_df.loc[index_with_max_salary_mid]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [77]:
#2
index_with_min_salary_starting = clean_df['Starting Median Salary'].idxmin()
clean_df.loc[index_with_min_salary_starting]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [78]:
#3
index_with_min_salary_mid = clean_df['Mid-Career Median Salary'].idxmin()
clean_df.loc[index_with_min_salary_mid]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [79]:
#Let's calculate difference between 90th percentile and 10th percentile
spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [81]:
low_risk = clean_df.sort_values('Spread',ascending = False)
low_risk[['Undergraduate Major', 'Spread']].head(3)

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0

1. Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile.

2. Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation.

In [86]:
#1
clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending = False).head(3)

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM

In [90]:
#2
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major','Spread']].head(3)

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0

In [94]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [96]:
# clean_df.groupby('Group').mean()

TypeError: agg function failed [how->mean,dtype->object]